"""Gör platsinformation valfri

Revision ID: 8a13b81b2e01
Revises: 
Create Date: 2025-04-23 18:35:05.909137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a13b81b2e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('location_city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('location_city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
